"""visit update statuses procedure

Revision ID: 4cb139ff6dc8
Revises: 64b1db624de5
Create Date: 2025-12-22 14:03:34.338053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cb139ff6dc8'
down_revision: Union[str, Sequence[str], None] = '64b1db624de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
        # ✅ Переименовываем старые enum-типы в новые имена
    op.execute("ALTER TYPE paymentstatus RENAME TO payment_status")
    op.execute("ALTER TYPE visitstatus RENAME TO visit_status")

    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_id'), 'procedure', ['id'], unique=False)
    op.create_index(op.f('ix_procedure_name'), 'procedure', ['name'], unique=True)
    op.add_column('visit', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.add_column('visit', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('visit', 'procedure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('visit', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('visit', 'payment_status',
               existing_type=postgresql.ENUM('paid', 'partial', 'unpaid', name='paymentstatus'),
               type_=sa.Enum('paid', 'partial', 'unpaid', name='payment_status'),
               existing_nullable=False)
    op.alter_column('visit', 'visit_status',
               existing_type=postgresql.ENUM('scheduled', 'in_progress', 'completed', name='visitstatus'),
               type_=sa.Enum('scheduled', 'in_progress', 'completed', name='visit_status'),
               existing_nullable=False)
    op.create_index(op.f('ix_visit_date'), 'visit', ['date'], unique=False)
    op.create_index(op.f('ix_visit_dentist_id'), 'visit', ['dentist_id'], unique=False)
    op.create_index(op.f('ix_visit_patient_id'), 'visit', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visit_procedure_id'), 'visit', ['procedure_id'], unique=False)
    op.create_foreign_key(None, 'visit', 'procedure', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_index(op.f('ix_visit_procedure_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_patient_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_dentist_id'), table_name='visit')
    op.drop_index(op.f('ix_visit_date'), table_name='visit')
    op.alter_column('visit', 'visit_status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', name='visit_status'),
               type_=postgresql.ENUM('scheduled', 'in_progress', 'completed', name='visitstatus'),
               existing_nullable=False)
    op.alter_column('visit', 'payment_status',
               existing_type=sa.Enum('paid', 'partial', 'unpaid', name='payment_status'),
               type_=postgresql.ENUM('paid', 'partial', 'unpaid', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('visit', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('visit', 'procedure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('visit', 'duration_minutes')
    op.drop_column('visit', 'procedure_id')
    op.drop_index(op.f('ix_procedure_name'), table_name='procedure')
    op.drop_index(op.f('ix_procedure_id'), table_name='procedure')
    op.drop_table('procedure')
    # ### end Alembic commands ###
    
